FROM ubuntu:latest

RUN apt-get update

RUN mkdir /home/wlug

RUN mkdir /home/wlug/starthere

RUN mkdir /home/wlug/egg

RUN mkdir /home/wlug/glass

RUN mkdir /home/wlug/magicspecs

RUN mkdir /home/wlug/window

RUN mkdir /home/wlug/thor

RUN mkdir /home/wlug/future

RUN mkdir /home/wlug/invisibleman

RUN mkdir /home/wlug/promise

RUN mkdir /home/wlug/word

RUN mkdir /home/wlug/tree

RUN mkdir /home/wlug/bank

WORKDIR /home/wlug/starthere

RUN echo "Break me to use me !!!">iamhint01

RUN echo "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae">iamhint00

RUN echo "consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio">iamhint02

RUN echo "eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur">iamhint03

RUN chmod 444 iamhint01

RUN chmod 444 iamhint02

RUN chmod 444 iamhint00

RUN chmod 444 iamhint03

WORKDIR /home/wlug/egg

RUN echo "iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!">iamhint01

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi repudiandae">iamhint00

RUN echo "What is always in front of you but can’t be seen?">iamhint02

RUN echo "eaque accusantium rerum! repudiandae similique  nemo autem. Veritatis obcaecati tenetur">iamhint03

RUN chmod 444 iamhint01

RUN chmod 444 iamhint02

RUN chmod 444 iamhint00

RUN chmod 444 iamhint03

WORKDIR /home/wlug/glass

RUN echo "iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!">iamhint02

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi repudiandae">iamhint01

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi">iamhint03

RUN echo "eaque accusantium rerum! repudiandae similique  nemo autem. Veritatis obcaecati tenetur">iamhint00

RUN chmod 444 iamhint01

RUN chmod 444 iamhint02

RUN chmod 444 iamhint00

RUN chmod 444 iamhint03

WORKDIR /home/wlug/future

RUN echo "iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!">iamhint02

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi repudiandae">iamhint03

RUN echo "Well, you found the first Part : {{{<KEY_1>}}}. Look for another, What can you break, even if you never pick it up or touch it?">iamhint00

RUN echo "eaque accusantium rerum! repudiandae similique  nemo autem. Veritatis obcaecati tenetur">iamhint01

RUN chmod 444 iamhint01

RUN chmod 444 iamhint02

RUN chmod 444 iamhint00

RUN chmod 444 iamhint03

WORKDIR /home/wlug/promise

RUN echo "iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!">iamhint00

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi repudiandae">iamhint01

RUN echo "I have branches, but no fruit, trunk or leaves. What am I?">iamhint02

RUN echo "eaque accusantium rerum! repudiandae similique  nemo autem. Veritatis obcaecati tenetur">iamhint03

RUN chmod 444 iamhint01

RUN chmod 444 iamhint02

RUN chmod 444 iamhint00

RUN chmod 444 iamhint03

WORKDIR /home/wlug/bank

RUN echo "iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!">iamhint01

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi repudiandae">iamhint02

RUN echo "What can you keep after giving to someone?">iamhint00

RUN echo "eaque accusantium rerum! repudiandae similique  nemo autem. Veritatis obcaecati tenetur">iamhint03

RUN chmod 444 iamhint01

RUN chmod 444 iamhint02

RUN chmod 444 iamhint00

RUN chmod 444 iamhint03

WORKDIR /home/wlug/word

RUN echo "iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!">iamhint03

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi repudiandae">iamhint02

RUN echo "Well, you found the second Part : {{{<KEY_2>}}}.\nCongratulations !!!">iamhint01

RUN echo "eaque accusantium rerum! repudiandae similique  nemo autem. Veritatis obcaecati tenetur">iamhint00

RUN chmod 444 iamhint01

RUN chmod 444 iamhint02

RUN chmod 444 iamhint00

RUN chmod 444 iamhint03

WORKDIR /home/wlug/magicspecs

RUN echo "iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!">iamhint00

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi repudiandae">iamhint01

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi">iamhint02

RUN echo "eaque accusantium rerum! repudiandae similique  nemo autem. Veritatis obcaecati tenetur">iamhint03

RUN chmod 444 iamhint01

RUN chmod 444 iamhint02

RUN chmod 444 iamhint00

RUN chmod 444 iamhint03

WORKDIR /home/wlug/window

RUN echo "iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!">iamhint02

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi repudiandae">iamhint01

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi">iamhint03

RUN echo "eaque accusantium rerum! repudiandae similique  nemo autem. Veritatis obcaecati tenetur">iamhint00

RUN chmod 444 iamhint01

RUN chmod 444 iamhint02

RUN chmod 444 iamhint00

RUN chmod 444 iamhint03

WORKDIR /home/wlug/thor

RUN echo "iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!">.iamhint01

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi repudiandae">.iamhint03

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi">.iamhint00

RUN echo "eaque accusantium rerum! repudiandae similique  nemo autem. Veritatis obcaecati tenetur">.iamhint02

RUN chmod 444 .iamhint01

RUN chmod 444 .iamhint02

RUN chmod 444 .iamhint00

RUN chmod 444 .iamhint03

WORKDIR /home/wlug/invisibleman

RUN echo "iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!">iamhint02

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi repudiandae">iamhint01

RUN echo "Impedit sit sunt quaerat, odit, molestiae quas vel sint commodi">iamhint03

RUN echo "eaque accusantium rerum! repudiandae similique  nemo autem. Veritatis obcaecati tenetur">iamhint00

RUN chmod 444 iamhint01

RUN chmod 444 iamhint02

RUN chmod 444 iamhint00

RUN chmod 444 iamhint03

WORKDIR /home

RUN echo "\n\n\n1) Hints are given for you to find the key !!!\n2) First Half will take you to Second Half, so don't miss it.\n3) Flag is concatenation of first and second half.\n\n\nPossible Commands for the task -> ls, cd, cat \n\n\nAll The Best !!!">README

RUN chmod 444 README

CMD ["/bin/bash"]
