FROM ubuntu:latest

RUN apt-get update

RUN mkdir /home/creator

RUN mkdir /home/wlug

WORKDIR /home/wlug

RUN echo "I am not the Desired one">ubuntu

RUN echo "Maybe, some Indian origin">.kali

RUN echo "Not even close">fedora

RUN echo "You Found Me, But What is The Flag??">garuda

RUN echo "No Way, it could be me">mint

RUN chmod 444 ubuntu

RUN chmod 444 .kali

RUN chmod 444 fedora

RUN chmod 444 garuda

RUN chmod 444 mint

WORKDIR /home/creator

RUN echo "Am I the key? Maybe Google me !!!">.directory

RUN chmod 444 .directory

WORKDIR /home

RUN echo "\n\n\n1) Find the favourite distro \n2) Password is not given directly. \n\n\nPossible Commands for the task -> ls, cd, cat \n\n\nAll The Best !!!">README

RUN chmod 444 README

CMD ["/bin/bash"]
