FROM ubuntu:latest

RUN apt-get update

RUN mkdir /home/wlug

RUN mkdir /home/wlug/linuxDiary3.0

RUN mkdir /home/wlug/linuxDiary3.0/cse

RUN mkdir /home/wlug/linuxDiary3.0/it

RUN mkdir /home/wlug/linuxDiary3.0/eletrical

RUN mkdir /home/wlug/linuxDiary3.0/mech

RUN mkdir /home/wlug/linuxDiary3.0/civil

RUN mkdir /home/wlug/linuxDiary3.0/electronics

WORKDIR /home/wlug/linuxDiary3.0/cse

RUN echo "maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer iamsomejewerisfilewithsomejewerisdata">answer00

RUN echo "iamsomejewerisfilewithsomejewerisdata maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer">answer01

RUN echo "Maybe, You can try Thermodynamics !!!">.answer02

RUN echo "maybeyoucantrysomeotherfile iamsomejewerisfilewithsomejewerisdata ormaybeicouldbetheanswerinsomeothercontainer">.answer03

RUN echo "againajewerisfile areyoueventrying makesuretocheckeverypossiblefile">answer04

RUN chmod 444 answer00

RUN chmod 444 answer01

RUN chmod 444 .answer02

RUN chmod 444 .answer03

RUN chmod 444 answer04

WORKDIR /home/wlug/linuxDiary3.0/it

RUN echo "Maybe Again, something related to Automation !!!">answer00

RUN echo "maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer iamsomejewerisfilewithsomejewerisdata">.answer01

RUN echo "maybeyoucantrysomeotherfile iamsomejewerisfilewithsomejewerisdata ormaybeicouldbetheanswerinsomeothercontainer">answer02

RUN echo "iamsomejewerisfilewithsomejewerisdata maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer">answer03

RUN echo "againajewerisfile areyoueventrying makesuretocheckeverypossiblefile">.answer04

RUN chmod 444 answer00

RUN chmod 444 .answer01

RUN chmod 444 answer02

RUN chmod 444 answer03

RUN chmod 444 .answer04

WORKDIR /home/wlug/linuxDiary3.0/electronics

RUN echo "maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer iamsomejewerisfilewithsomejewerisdata">.answer00

RUN echo "iamsomejewerisfilewithsomejewerisdata maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer">answer02

RUN echo "Maybe, You like Fluid Dynamics !!!">answer04

RUN echo "maybeyoucantrysomeotherfile iamsomejewerisfilewithsomejewerisdata ormaybeicouldbetheanswerinsomeothercontainer">answer03

RUN echo "againajewerisfile areyoueventrying makesuretocheckeverypossiblefile">.answer01

RUN chmod 444 .answer00

RUN chmod 444 .answer01

RUN chmod 444 answer02

RUN chmod 444 answer03

RUN chmod 444 answer04

WORKDIR /home/wlug/linuxDiary3.0/eletrical

RUN echo "maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer iamsomejewerisfilewithsomejewerisdata">answer03

RUN echo "iamsomejewerisfilewithsomejewerisdata maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer">answer01

RUN echo "Maybe, You Can Try Some Other Stream !!!">.answer02

RUN echo "maybeyoucantrysomeotherfile iamsomejewerisfilewithsomejewerisdata ormaybeicouldbetheanswerinsomeothercontainer">answer00

RUN echo "againajewerisfile areyoueventrying makesuretocheckeverypossiblefile">.answer04

RUN chmod 444 answer00

RUN chmod 444 answer01

RUN chmod 444 .answer02

RUN chmod 444 answer03

RUN chmod 444 .answer04

WORKDIR /home/wlug/linuxDiary3.0/mech

RUN echo "maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer iamsomejewerisfilewithsomejewerisdata">answer02

RUN echo "iamsomejewerisfilewithsomejewerisdata maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer">answer04

RUN echo "Congratulations, You are a Mech Student. Your Flag = {{{<KEY>}}}">.answer01

RUN echo "maybeyoucantrysomeotherfile iamsomejewerisfilewithsomejewerisdata ormaybeicouldbetheanswerinsomeothercontainer">answer03

RUN echo "againajewerisfile areyoueventrying makesuretocheckeverypossiblefile">.answer00

RUN chmod 444 .answer00

RUN chmod 444 .answer01

RUN chmod 444 answer02

RUN chmod 444 answer03

RUN chmod 444 answer04

WORKDIR /home/wlug/linuxDiary3.0/civil

RUN echo "maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer iamsomejewerisfilewithsomejewerisdata">.answer01

RUN echo "iamsomejewerisfilewithsomejewerisdata maybeyoucantrysomeotherfile ormaybeicouldbetheanswerinsomeothercontainer">.answer02

RUN echo "Hey, Maybe I know you. You could be a Mech Student !!!">.answer04

RUN echo "maybeyoucantrysomeotherfile iamsomejewerisfilewithsomejewerisdata ormaybeicouldbetheanswerinsomeothercontainer">.answer03

RUN echo "againajewerisfile areyoueventrying makesuretocheckeverypossiblefile">.answer00

RUN chmod 444 .answer00

RUN chmod 444 .answer01

RUN chmod 444 .answer02

RUN chmod 444 .answer03

RUN chmod 444 .answer04

WORKDIR /home/wlug/linuxDiary3.0

RUN echo "\n\n\n1) You are Starting Inside \home\wlug\linuxDiary3.0 \n2) You forget your branch and need to find it from the 6 branches available. \n3) Maybe Hints are there, do look for them. \n\n\nPossible Commands for the task -> ls, cd, cat \n\n\nAll The Best !!!">README

RUN chmod 444 README

CMD ["/bin/bash"]
