FROM ubuntu:latest

RUN apt-get update

RUN mkdir /home/wlug

WORKDIR /home/wlug

RUN echo "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,\nmolestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum\nnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium\noptio, eaque rerum! Provident similique accusantium nemo autem. Veritatis\nobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam\nIf I am the answer, then Flag = {{{<KEY>}}}\nnihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,\ntenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit,\nquia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos ">.itmaybehere00

RUN chmod -rwx .itmaybehere00

RUN echo "Lorem ipsum dolor sit amet \nconsectetur adipisicing elit. Maxime mollitia,\nmolestiae quas vel sint commodi \nrepudiandae consequuntur voluptatum laborum\nnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium\noptio, eaque rerum!\nIf I am the answer, then Flag = {{{<KEY>}}}\n Provident similique accusantium nemo autem. Veritatis\nobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam\nnihil, eveniet aliquid culpa officia aut! \nImpedit sit sunt quaerat, odit,\ntenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit,\nquia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos ">.itmaybehere01

RUN chmod -rwx .itmaybehere01

RUN echo "Lorem ipsum dolor sit amet consectetur adipisicing elit. \nMaxime mollitia,\nmolestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum\nnumquam blanditiis harum \nquisquam eius sed odit fugiat \niusto fuga praesentium\noptio, eaque rerum! \nIf I am the answer, then Flag = {{{<KEY>}}}\nProvident similique accusantium nemo autem. Veritatis\nobcaecati tenetur iure eius earum ut \nmolestias architecto voluptate aliquam\nnihil, eveniet aliquid culpa officia aut! \nImpedit sit sunt quaerat, odit,\ntenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit,\nquia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos ">.itmaybehere02

RUN chmod -rwx .itmaybehere02

RUN echo "Lorem ipsum dolor \nsit amet consectetur \nadipisicing elit. Maxime mollitia,\nmolestiae quas vel sint commodi \nrepudiandae consequuntur voluptatum laborum\nnumquam blanditiis harum quisquam \neius sed odit fugiat iusto fuga praesentium\noptio, eaque rerum! Provident similique \nIf I am the answer, then Flag = {{{<KEY>}}}\naccusantium nemo autem. Veritatis\nobcaecati tenetur iure eius earum \nut molestias architecto voluptate aliquam\nnihil, eveniet aliquid \nculpa officia aut! Impedit sit \nsunt quaerat, odit,\ntenetur error, harum nesciunt ipsum debitis \nquas aliquid. Reprehenderit,\nquia. Quo neque error repudiandae \nfuga? Ipsa laudantium molestias eos ">.itmaybehere03

RUN chmod -rwx .itmaybehere03

WORKDIR /home

RUN echo "\n\n\n1) Look for the flag\n2) The owner's favourite number is 15\n\n\nPossible Commands -> ls, cd, wc \nAll The Best !!!">README

RUN chmod 444 README

CMD ["/bin/bash"]
