name: linuxdiary-3.0

on: [push]

jobs:
  publish-updated:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build updated dockerfiles
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/scripts/linuxdiary-3.0.sh"
        ${GITHUB_WORKSPACE}/.github/scripts/linuxdiary-3.0 ${API_KEY}

