name: linuxdiary-3.0

on: [push]

jobs:
  publish-updated:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: wcewlug
        password: ${{ secrets.PAT }}

    - name: Build updated dockerfiles
      run: |
        rm -f ${GITHUB_WORKSPACE}/.github/updates/linuxdiary-3.0
        touch ${GITHUB_WORKSPACE}/.github/updates/linuxdiary-3.0
        python ${GITHUB_WORKSPACE}/.github/scripts/linuxdiary-3.0/linuxdiary-3.0.py
        ${GITHUB_WORKSPACE}/.github/scripts/linuxdiary-3.0/buildAndUpdate.sh
        rm -f ${GITHUB_WORKSPACE}/.github/updates/linuxdiary-3.0

    - name: Push hash changes
      run: |
        git config --global user.name 'Walchand Linux Users' Group'
        git config --global user.email 'wce.wlugclub@gmail.com'
        git commit -am "Hash Updated"
        git push
